[package]
name = "renoired"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bytemuck = { version = "1.16.0", features = ["derive"] }
cgmath = "0.18.0"
env_logger = "0.11.3"
log = "0.4.21"
pollster = "0.3.0"
raw-window-handle = "0.6.2"
wgpu = "0.20.0"
winit = "0.30.0"

[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]
